name: AIYP
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  #Firebase
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0
  firebase_storage: ^7.0.0
  firebase_database: ^6.0.0
  provider: ^4.3.2+3

  #Alertas
  rflutter_alert: ^1.1.0
  #Web View
  webview_flutter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true